# Generated by Django 3.2.6 on 2021-12-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('linkedinname', models.CharField(max_length=200)),
                ('shodanname', models.CharField(max_length=200)),
                ('licensetype', models.CharField(max_length=50)),
                ('licensestartdate', models.DateField()),
                ('licenseenddate', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('activityarea', models.CharField(max_length=100)),
                ('securitygrade', models.CharField(max_length=100)),
                ('companysize', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('email', models.CharField(max_length=100)),
                ('username', models.CharField(editable=False, max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('apikey', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentid', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('itemorder', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('is_seen', models.BooleanField()),
                ('has_item', models.BooleanField()),
                ('icon', models.CharField(max_length=50, null=True)),
                ('alarmtype_ids', models.CharField(max_length=100, null=True)),
            ],
            options={
                'ordering': (['id'],),
            },
        ),
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.UniqueConstraint(fields=('address',), name='menu_address_unique'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('name',), name='company_name_unique'),
        ),
    ]
