# Generated by Django 3.2.6 on 2021-12-20 08:49

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_manuel', models.BooleanField()),
                ('alarm_type_id', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('severity', models.CharField(max_length=20)),
                ('description', ckeditor.fields.RichTextField()),
                ('mitigation', ckeditor.fields.RichTextField()),
                ('source', models.TextField()),
                ('analyst_state', models.IntegerField(editable=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(editable=False, max_length=50)),
                ('ip', models.CharField(editable=False, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='AlarmType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('explain', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=20)),
                ('is_manuel', models.BooleanField(default=True)),
                ('monitor', models.BooleanField(default=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('mitigation', ckeditor.fields.RichTextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(editable=False, max_length=50)),
                ('ip', models.CharField(editable=False, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phishing_url', models.CharField(default='', max_length=200)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
                ('registrar_name', models.CharField(default='', max_length=200)),
                ('registrar_company', models.CharField(default='', max_length=200)),
                ('registrant_name', models.CharField(default='', max_length=200)),
                ('registrant_country', models.CharField(default='', max_length=200)),
                ('leak_source', models.CharField(default='', max_length=200)),
                ('screenshot', models.ImageField(blank=True, default='path/to/my/default/image.jpg', upload_to='images')),
                ('port', models.CharField(default='', max_length=200)),
                ('protocol', models.CharField(default='', max_length=200)),
                ('cvss', models.CharField(default='', max_length=200)),
                ('cve', models.CharField(default='', max_length=200)),
                ('url', models.CharField(default='', max_length=200)),
                ('subdomain', models.CharField(default='', max_length=200)),
                ('ns', models.CharField(default='', max_length=200)),
                ('soa', models.CharField(default='', max_length=200)),
                ('txt', models.CharField(default='', max_length=200)),
                ('mx_old_record', models.CharField(default='', max_length=200)),
                ('mx_new_record', models.CharField(default='', max_length=200)),
                ('ns_old_record', models.CharField(default='', max_length=200)),
                ('ns_new_record', models.CharField(default='', max_length=200)),
                ('soa_old_record', models.CharField(default='', max_length=200)),
                ('soa_new_record', models.CharField(default='', max_length=200)),
                ('txt_old_record', models.CharField(default='', max_length=200)),
                ('fqdn', models.CharField(default='', max_length=200)),
                ('ip', models.CharField(default='', max_length=200)),
                ('reverse_dns', models.CharField(default='', max_length=200)),
                ('is_private', models.CharField(default='', max_length=200)),
                ('domain', models.CharField(default='', max_length=200)),
                ('row_data_old', models.CharField(default='', max_length=200)),
                ('row_data_new', models.CharField(default='', max_length=200)),
                ('expiration_days', models.CharField(default='', max_length=200)),
                ('status_code', models.CharField(default='', max_length=200)),
                ('server_header', models.CharField(default='', max_length=200)),
                ('title_old', models.CharField(default='', max_length=200)),
                ('title_new', models.CharField(default='', max_length=200)),
                ('server_header_old', models.CharField(default='', max_length=200)),
                ('server_header_new', models.CharField(default='', max_length=200)),
                ('cert_name', models.CharField(default='', max_length=200)),
                ('grade', models.CharField(default='', max_length=200)),
                ('level', models.CharField(default='', max_length=200)),
                ('name', models.CharField(default='', max_length=200)),
                ('version', models.CharField(default='', max_length=200)),
                ('asset', models.CharField(default='', max_length=200)),
                ('explanation', models.CharField(default='', max_length=200)),
                ('references', models.CharField(default='', max_length=200)),
                ('service', models.CharField(default='', max_length=200)),
                ('summary', models.CharField(default='', max_length=200)),
                ('product', models.CharField(default='', max_length=200)),
                ('dmarc_old_record', models.CharField(default='', max_length=200)),
                ('dmarc_new_record', models.CharField(default='', max_length=200)),
                ('spf_old_record', models.CharField(default='', max_length=200)),
                ('spf_new_record', models.CharField(default='', max_length=200)),
                ('assets', models.CharField(default='', max_length=200)),
                ('username_mail', models.CharField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=200)),
                ('github_repo_name', models.CharField(default='', max_length=200)),
                ('txt_new_record', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('form_name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlarmTypeLicenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarmtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyst.alarmtype')),
                ('licensetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyst.licensetype')),
            ],
        ),
        migrations.CreateModel(
            name='AlarmTypeContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarmtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyst.alarmtype')),
                ('contenttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyst.contenttype')),
            ],
        ),
        migrations.AddField(
            model_name='alarmtype',
            name='contenttypes',
            field=models.ManyToManyField(through='analyst.AlarmTypeContentType', to='analyst.ContentType'),
        ),
        migrations.AddField(
            model_name='alarmtype',
            name='licensetypes',
            field=models.ManyToManyField(through='analyst.AlarmTypeLicenseType', to='analyst.LicenseType'),
        ),
        migrations.CreateModel(
            name='AlarmContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyst.alarm')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyst.content')),
            ],
        ),
        migrations.CreateModel(
            name='AlarmCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_state', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(editable=False, max_length=50)),
                ('ip', models.CharField(editable=False, max_length=40)),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyst.alarm')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.company')),
            ],
        ),
        migrations.AddField(
            model_name='alarm',
            name='companies',
            field=models.ManyToManyField(through='analyst.AlarmCompany', to='home.Company'),
        ),
        migrations.AddField(
            model_name='alarm',
            name='contents',
            field=models.ManyToManyField(through='analyst.AlarmContent', to='analyst.Content'),
        ),
        migrations.AddConstraint(
            model_name='alarmtype',
            constraint=models.UniqueConstraint(fields=('title',), name='alarmtype_title_unique'),
        ),
    ]
